In [7]:
for i in range(1, 11):
    if i != 3 and i != 8:
        print(i)


1
2
4
5
6
7
9
10


In [9]:
#Find the first number divisible by 7 between 1 and 100
for i in range(1,101):
    if i%7==0:
        print(i)
        break
    


7


In [11]:
#Count vowels in a string
s ="Programming"
count=0
for ch in s:
    if ch in 'aeiou':
        count+=1
print(count)        
        

4


In [12]:
for i in range(1, 31):
    if i % 5 != 0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29


In [13]:
#Print 1–50, skip multiples of 3, skip numbers ending with 7, stop if number becomes 40
for i in range(1, 51):
    if i == 40:
        break
    if i % 3 == 0 or i % 10 == 7:
        continue
    print(i)

1
2
4
5
8
10
11
13
14
16
19
20
22
23
25
26
28
29
31
32
34
35
38


In [ ]:
t = (1, 2, 2, 3, 4, 4, 5)
result = ()

for i in t:
    if i not in result:
        result += (i,)

print(result)

In [16]:
lst = [1, 2, 3, 4, 5, 6]
mid = len(lst) // 2

first_half = lst[:mid]
second_half = lst[mid:]

print(first_half)
print(second_half)

[1, 2, 3]
[4, 5, 6]


In [17]:
a = [1, 2, 3, 4]
b = [3, 4, 5, 6]

common = []

for i in a:
    if i in b and i not in common:
        common.append(i)

print(common)

[3, 4]


In [ ]:
lst = [1, 2, 3, 2, 1]

if lst == lst[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")


In [18]:
s = "programming"
duplicates = []

for ch in s:
    if s.count(ch) > 1 and ch not in duplicates:
        duplicates.append(ch)

print(duplicates)


['r', 'g', 'm']


In [19]:
s = "programming"
result = ""

for ch in s:
    if ch not in result:
        result += ch

print(result)

progamin


In [20]:
s = "Programming"
result = ""

for ch in s:
    if ch.lower() in "aeiou":
        result += "*"
    else:
        result += ch

print(result)


Pr*gr*mm*ng


In [23]:
sentence = "Python is very easy to learn"
words = sentence.split()

print(len(words))


6


In [26]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [27]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
arr=np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Data Type",arr.dtype)
print("Data Type",arr.shape)
print("Data Type",arr.ndim)

Data Type int64
Data Type (2, 3)
Data Type 2


In [34]:
list1=[1,2,3,4,5]
arr=np.array(list1)
print(arr)


[1 2 3 4 5]


In [35]:
#Create an identity matrix of size 4 × 4
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
#Generate a random array of size 5
random_arr=np.random.rand(5)
print(random_arr)

[0.89916958 0.11354911 0.53113012 0.56213923 0.08984675]


In [38]:
#Access the third element of a 1-D array
list1=[1,2,3,4,5]
list1[2]


3

In [41]:
data=np.array([[1,2,3,4,5],
               [1,2,3,4,5]])
print(data[1,2])


3


In [46]:
numbers = np.array([10, 15, 30, 3, 50])

even_numbers = numbers[numbers % 2 == 0]

print("Even numbers:", even_numbers)


Even numbers: [10 30 50]


In [47]:
numbers = np.array([10, 15, 30, 3, 50])
rev = numbers[::-1]
print("Reversed array:", rev)

Reversed array: [50  3 30 15 10]


In [48]:
numbers = np.array([10, 15, 30, 3, 50])
print("Maximum value:", np.max(numbers))

Maximum value: 50


In [49]:
numbers = np.array([10, 15, 30, 3, 50])
print("Minimum value:", np.min(numbers))

Minimum value: 3


In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b
print(result)

[5 7 9]


In [51]:
arr = np.array([1, 2, 3, 4])

result = arr * 5
print(result)

[ 5 10 15 20]


In [52]:
arr = np.arange(1, 13)
reshaped = arr.reshape(3, 4)

print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

flat = arr.flatten()
print(flat)

[1 2 3 4 5 6]


In [54]:
arr=np.array([[1,2,3],[4,5,6]])
row_sum=arr.sum(axis=1)
print(row_sum)

[ 6 15]


In [55]:
arr=np.array([[1,2,3],[4,5,6]])
row_sum=arr.mean()
print(row_sum)

3.5
